#!/usr/bin/env bash
set -e

source $(dirname $0)/common.sh

BASH_HISTORY_FILE=${HOME:?}/.cache/haskell-docker-bash-history

create_bash_history_file() {
    if [ ! -e ${BASH_HISTORY_FILE:?} ]; then
        touch ${BASH_HISTORY_FILE:?}
    fi
}

graphical_options() {
    echo \
        --env DISPLAY \
        --gpus all \
        --volume /tmp/.X11-unix:/tmp/.X11-unix
}

run_container() {
    docker run \
        --interactive \
        --name ${CONTAINER_NAME} \
        --env NVIDIA_VISIBLE_DEVICES=all \
        --env NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility \
        --rm \
        --tty \
        --user user \
        --volume $PWD:/workdir:rw \
        --volume ${BASH_HISTORY_FILE:?}:/home/user/.bash_history:rw \
        $(graphical_options) \
        ${IMAGE_NAME} \
        $@ || exit -1
}

create_bash_history_file
run_container $@
